CREATE TABLE IF NOT EXISTS growths (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid          UUID   NOT NULL,
  started_at    TIMESTAMP NOT NULL, 
  baby_weight   INT NOT NULL,
  baby_length   INT NULL,
  baby_head     INT NULL,
  note          TEXT NULL,

  baby_id       BIGINT REFERENCES babies ON DELETE CASCADE,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_growths_modtime BEFORE UPDATE ON growths FOR EACH ROW EXECUTE PROCEDURE  update_modified_column();